#!/bin/sh

# doit
# convert rams from md to html (via json)
# jcl/othinking/2016-07-31

set -e

for f in master/*.md; do
	b=$( basename "$f" .md )

	# build the json file if master changed
	#
	if [ ! -f out/$b.json -o master/$b.md -nt out/$b.json ]; then
		echo "making out/$b.json"
		bin/rams_mdtojson master/$b.md > out/$b.json.tmp
		mv out/$b.json.tmp out/$b.json
	fi

	# build the html file if json changed
	#
	if [ ! -f out/$b.html -o out/$b.json -nt out/$b.html ]; then
		echo "making out/$b.html"
		bin/rams_jsontonice out/$b.json > out/$b.html.tmp
		mv out/$b.html.tmp out/$b.html
	fi

	# until we get good pictures
	# make a fake one
	#
	if [ ! -f images/$b.jpg ]; then
		echo "making images/$b.jpg"
		bin/mkimage images/$b.jpg 400 300 0xeeeeee 0x000000 "placeholder for $b"
	fi
done

echo "making index.html"
bin/mksummary master/*.md > index.html.tmp && mv index.html.tmp index.html

# end
