#!/bin/sh

# publish
# publish rams onto discourse
# jcl/othinking/2016-07-31

set -e

. ./discourse.config

for f in master/*.md; do
	b=$( basename "$f" .md )

	# publish a dummy if nothing yet
	#	this creates the topic
	#
	if [ ! -f out/$b.discourse ]; then
		echo "publishing dummy $b"
		topic="$b (`date '+%Y-%m-%d %H:%M:%S'`)"
		bin/discourse_createtopic $CAT "$b" > out/$b.discourse.tmp
		mv out/$b.discourse.tmp out/$b.discourse
		touch -r $f out/$b.discourse

		echo "  (sleeping because of rate limits)"
		sleep 1
	fi
done

echo -n '' > /tmp/$$.tool.tmp
for f in out/*.discourse; do
	b=$( basename "$f" .discourse )
	toolname=$( awk '(NR==2){print; exit(0);}' master/$b.md )
	echo "$b.md\t$toolname" >> /tmp/$$.tool.tmp
done

# check no tool is defined in more than one file
#	we use the 'nice tool name' in the md file
#	to name the discourse articles
#	if we have a duplicate it will make a cryptic
#	"422 Unprocessable Entity"
#	(if we pulled the api response as json it
#	would normally be a clear error)
#
cat /tmp/$$.tool.tmp \
| awk -F\\t '
{	if (x[$2]) {
		printf("%s: toolname \"%s\" already in %s\n",
			$1, $2, x[$2]);
		exit(1);
	}
	x[$2] = $1;
}
'

for f in out/*.discourse; do
	b=$( basename "$f" .discourse )
	if [ out/$b.html -nt out/$b.discourse ]; then
		echo "==== updating $b ===="

		# extract our topic and post ids rough from json
		#
		topicid=$( cat out/$b.discourse | tr , '\n' | tr -d '"' | awk -F: '($1=="topic_id"){print $2;exit(0);}' )
		postid=$( cat out/$b.discourse | tr , '\n' | tr -d '"{' | awk -F: '($1=="id"){print $2;exit(0);}' )
		echo "  topic $topicid post $postid"

		# extract our human title of toolname rough from markdown
		#
		toolname=$( awk '(NR==2){print; exit(0);}' master/$b.md )
		echo "  toolname /$toolname/"

		# do the updates
		#	we update the topic to something unique
		#	as belt-and-braces against duplicate titles
		#
		topic="$toolname (`date '+%Y-%m-%d %H:%M:%S'`)"
		echo "  updating topic $topicid to be '$topic'"
		bin/discourse_updatetopic "$topicid" "$topic" > /tmp/$b.up1
		topic="$toolname (Risk Assessment)"
		echo "  updating topic $topicid to be '$topic'"
		bin/discourse_updatetopic "$topicid" "$topic" > /tmp/$b.up2

		echo "  updating post $postid to new contents"
		bin/discourse_updatepost "$postid" "out/$b.body" > /tmp/$b.up3

		# say done
		#
		touch out/$b.discourse
	else
		echo "good $b"
	fi
done

echo "happy ending"

# end
