#!/bin/sh

# publish
# publish rams onto discourse
# jcl/othinking/2016-07-31

set -e

. ./discourse.config

for f in master/*.md; do
	b=$( basename "$f" .md )

	# publish a dummy if nothing yet
	#	this creates the topic
	#
	if [ ! -f out/$b.discourse ]; then
		echo "publishing dummy $b"
		topic="$b (`date '+%Y-%m-%d %H:%M:%S'`)"
		bin/discourse_createtopic $CAT "$b" > out/$b.discourse.tmp
		mv out/$b.discourse.tmp out/$b.discourse
		touch -r $f out/$b.discourse

		echo "  (sleeping because of rate limits)"
		sleep 1
	fi
done

for f in out/*.discourse; do
	b=$( basename "$f" .discourse )
	if [ out/$b.html -nt out/$b.discourse ]; then
		echo "updating $b"

		# extract our topic and post ids rough from json
		#
		topicid=$( cat out/$b.discourse | tr , '\n' | tr -d '"' | awk -F: '($1=="topic_id"){print $2;exit(0);}' )
		postid=$( cat out/$b.discourse | tr , '\n' | tr -d '"{' | awk -F: '($1=="id"){print $2;exit(0);}' )
		echo "  topic $topicid post $postid"

		# extract our human title of toolname rough from markdown
		#
		toolname=$( awk '(NR==2){print; exit(0);}' master/$b.md )
		echo "  toolname /$toolname/"

		# create a temporary html just of the body
		#
		cat out/$b.html \
		| tr -d '\n' \
		| sed 's/^.*<body>//' \
		| sed 's/<\/body>.*$//' > /tmp/$$.tmp

		# do the updates
		#
		topic="$toolname (`date '+%Y-%m-%d %H:%M:%S'`)"
		echo "  updating topic $topicid to be '$topic'"
		bin/discourse_updatetopic "$topicid" "$topic"
		topic="$toolname (Risk Assessment)"
		echo "  updating topic $topicid to be '$topic'"
		bin/discourse_updatetopic "$topicid" "$topic"
		echo "  updating post $postid to new contents"
		bin/discourse_updatepost "$postid" "/tmp/$$.tmp"
		rm -f /tmp/$$.tmp

		# say done
		#
		touch out/$b.discourse
	else
		echo "good $b"
	fi
done

echo "happy ending"

# end
